String.prototype.includes('s')
String.prototype.trim()
String.prototype.trimStart()
String.prototype.trimEnd()
String.prototype.replaceAll('s', 't')
String.prototype.startsWith('s')
String.prototype.endsWith('s')
